// Generate Vue components from the exported SVGs.
//
// The SVGs in `icons/` are the source of truth; this restates them as Vue 3
// functional components using Vue's `h()` render function so app code can
// `import { Check } from "@keyline-icons/vue"` cleanly. Run `npm run icons:vue`
// after `icons:build`.
//
//   node pipeline/build-vue.mjs [--check]
//
// --check writes nothing and exits non-zero if the output would differ, the same
// contract `build.mjs --check` offers for icons/. It closes the window between
// renaming an icon and regenerating: until this runs, the old component is still
// exported, so `tsc` type-checks the app against a module the set no longer
// backs, and the app renders a glyph that is no longer in icons/.

import { mkdir, readdir, readFile, writeFile } from "node:fs/promises"
import { existsSync } from "node:fs"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"

const ROOT = fileURLToPath(new URL("..", import.meta.url))

/**
 * One entry per generated module in packages/vue/src/.
 *
 * `duotone` and `fill` go to the package only. They are separate modules
 * rather than one file with a `weight` prop. The three styles do not cover the
 * same icons — 414, 340 and 305 — so a single component taking a weight would
 * have to accept a combination that does not exist and decide what to do at
 * runtime. A missing import is a build error, which is the right time to find out.
 */
const vue = (file) => [
  `packages/vue/src/${file}`,
  join(ROOT, "packages", "vue", "src", file),
]

const VUE_MODULES = [
  { style: "stroke", corners: "regular", outs: [vue("index.ts")] },
  { style: "two-tone", corners: "regular", outs: [vue("two-tone.ts")] },
  { style: "duotone", corners: "regular", outs: [vue("duotone.ts")] },
  { style: "fill", corners: "regular", outs: [vue("fill.ts")] },

  /*
   * The sharp half, three more entry points and no renamed export.
   *
   * The style axis is already spelled as entry points — `@keyline-icons/vue/sharp`
   * and `/sharp/duotone`. Every existing import goes on resolving to exactly
   * the component it resolved to before.
   */
  { style: "stroke", corners: "sharp", outs: [vue("sharp.ts")] },
  { style: "two-tone", corners: "sharp", outs: [vue("sharp-two-tone.ts")] },
  { style: "duotone", corners: "sharp", outs: [vue("sharp-duotone.ts")] },
  { style: "fill", corners: "sharp", outs: [vue("sharp-fill.ts")] },
]

const check = process.argv.includes("--check")

const c = (n, s) => `\x1b[${n}m${s}\x1b[0m`

/** Attributes the wrapper supplies itself, so they must not be re-emitted. */
const ROOT_DROP = new Set(["width", "height", "xmlns", "viewBox"])

const ATTR = /([\w-]+)="([^"]*)"/g
const TAG = /<(path|circle|rect|line|polyline|polygon|ellipse)\b([^>]*?)\/?>/g

const attrs = (chunk) => [...chunk.matchAll(ATTR)].map(([, k, v]) => [k, v])

const pascal = (name) =>
  name
    .split("-")
    .map((part) => part[0].toUpperCase() + part.slice(1))
    .join("")

function jsValue(value) {
  return /^-?\d+(\.\d+)?$/.test(value) ? value : JSON.stringify(value)
}

function vueObj(pairs) {
  if (pairs.length === 0) return "{}"
  return "{" + pairs.map(([k, v]) => `"${k}": ${jsValue(v)}`).join(", ") + "}"
}

/**
 * The wrapper is emitted into every module rather than imported from a shared
 * one. Fifteen duplicated lines buys each module the property that matters
 * more: importing `@keyline-icons/vue/fill` pulls in that file and nothing else.
 */
const vueHeader = (dir) => `// GENERATED BY pipeline/build-vue.mjs — DO NOT EDIT.
// Source: ${dir}/*.svg. Regenerate with \`npm run icons:vue\`.

import { h, type SVGAttributes } from "vue"

export type IconProps = SVGAttributes & {
  /** Rendered box in px, set as both width and height. Defaults to 24. */
  size?: number | string
}

/**
 * Shared wrapper. Presentation attributes come from each icon's own root — a
 * pure-fill drawing carries no stroke, and forcing one on paints an outline
 * over every knockout — so they are spread by the generated component, not
 * hardcoded here.
 */
function Icon(rootProps: IconProps, userProps: IconProps, children?: any) {
  const { size = 24, ...rest } = userProps
  return h(
    "svg",
    {
      xmlns: "http://www.w3.org/2000/svg",
      viewBox: "0 0 24 24",
      width: size,
      height: size,
      "aria-hidden": "true",
      focusable: "false",
      ...rootProps,
      ...rest,
    },
    children
  )
}
`

async function build(style, corners) {
  const rel = corners === "sharp" ? `icons/sharp/${style}` : `icons/${style}`
  const dir = join(ROOT, rel)
  const files = (await readdir(dir)).filter((f) => f.endsWith(".svg")).sort()

  const components = []
  for (const file of files) {
    const name = file.slice(0, -4)
    const src = await readFile(join(dir, file), "utf8")

    const open = src.match(/<svg\b([^>]*)>/)?.[1] ?? ""
    const root = attrs(open).filter(([k]) => !ROOT_DROP.has(k))

    const body = [...src.matchAll(TAG)]
      .map(([, el, chunk]) => {
        return `      h("${el}", ${vueObj(attrs(chunk))})`
      })
      .join(",\n")

    components.push(
      `export function ${pascal(name)}(props: IconProps = {}) {\n` +
        `  return Icon(${vueObj(root)}, props, [\n` +
        `${body}\n` +
        `  ])\n` +
        `}`
    )
  }

  return {
    text: `${vueHeader(rel)}\n${components.join("\n\n")}\n`,
    count: components.length,
    rel,
  }
}

const built = []
for (const mod of VUE_MODULES)
  built.push({ ...mod, ...(await build(mod.style, mod.corners)) })

if (check) {
  let drift = false
  for (const { rel, outs, text } of built) {
    for (const [label, path] of outs) {
      const prev = existsSync(path) ? await readFile(path, "utf8") : null
      if (prev === text) continue
      const why = prev === null ? "does not exist" : `is out of sync with ${rel}/`
      console.error(`  ${c(33, "DRIFT")} ${label} ${why}`)
      drift = true
    }
  }
  if (drift) {
    console.error(`\nRun: node pipeline/build-vue.mjs`)
    process.exit(1)
  }
  const targets = built.reduce((n, m) => n + m.outs.length, 0)
  const summary = built
    .map((m) => `${m.corners === "sharp" ? "sharp " : ""}${m.style} ${m.count}`)
    .join(", ")
  console.log(c(32, `${targets} generated Vue modules in sync with icons/ (${summary})`))
} else {
  for (const { outs, text, count } of built) {
    for (const [label, path] of outs) {
      await mkdir(dirname(path), { recursive: true })
      await writeFile(path, text, "utf8")
      console.log(`Wrote ${count} components to ${label}`)
    }
  }
}
