// Generate Svelte components from the exported SVGs.
//
// The SVGs in `icons/` are the source of truth; this restates them as Svelte
// components so app code can `import { Check } from "@keyline-icons/svelte"` cleanly.
// Run `npm run icons:svelte` after `icons:build`.
//
//   node pipeline/build-svelte.mjs [--check]
//
// --check writes nothing and exits non-zero if the output would differ, the same
// contract `build.mjs --check` offers for icons/.

import { mkdir, readdir, readFile, writeFile } from "node:fs/promises"
import { existsSync } from "node:fs"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"

const ROOT = fileURLToPath(new URL("..", import.meta.url))

const svelte = (file) => [
  `packages/svelte/src/${file}`,
  join(ROOT, "packages", "svelte", "src", file),
]

const SVELTE_MODULES = [
  { style: "stroke", corners: "regular", outs: [svelte("index.ts")] },
  { style: "two-tone", corners: "regular", outs: [svelte("two-tone.ts")] },
  { style: "duotone", corners: "regular", outs: [svelte("duotone.ts")] },
  { style: "fill", corners: "regular", outs: [svelte("fill.ts")] },

  { style: "stroke", corners: "sharp", outs: [svelte("sharp.ts")] },
  { style: "two-tone", corners: "sharp", outs: [svelte("sharp-two-tone.ts")] },
  { style: "duotone", corners: "sharp", outs: [svelte("sharp-duotone.ts")] },
  { style: "fill", corners: "sharp", outs: [svelte("sharp-fill.ts")] },
]

const check = process.argv.includes("--check")
const c = (n, s) => `\x1b[${n}m${s}\x1b[0m`

/** Attributes the wrapper supplies itself, so they must not be re-emitted. */
const ROOT_DROP = new Set(["width", "height", "xmlns", "viewBox"])

const ATTR = /([\w-]+)="([^"]*)"/g
const TAG = /<(path|circle|rect|line|polyline|polygon|ellipse)\b([^>]*?)\/?>/g

const attrs = (chunk) => [...chunk.matchAll(ATTR)].map(([, k, v]) => [k, v])

const pascal = (name) =>
  name
    .split("-")
    .map((part) => part[0].toUpperCase() + part.slice(1))
    .join("")

function svelteAttrs(pairs) {
  if (pairs.length === 0) return ""
  return pairs.map(([k, v]) => ` ${k}="${v}"`).join("")
}

function svelteObj(pairs) {
  if (pairs.length === 0) return "{}"
  return "{" + pairs.map(([k, v]) => `"${k}": ${JSON.stringify(v)}`).join(", ") + "}"
}

const svelteHeader = (dir) => `// GENERATED BY pipeline/build-svelte.mjs — DO NOT EDIT.
// Source: ${dir}/*.svg. Regenerate with \`npm run icons:svelte\`.

import { createIcon } from "./create-icon"
`

async function build(style, corners) {
  const rel = corners === "sharp" ? `icons/sharp/${style}` : `icons/${style}`
  const dir = join(ROOT, rel)
  const files = (await readdir(dir)).filter((f) => f.endsWith(".svg")).sort()

  const components = []
  for (const file of files) {
    const name = file.slice(0, -4)
    const src = await readFile(join(dir, file), "utf8")

    const open = src.match(/<svg\b([^>]*)>/)?.[1] ?? ""
    const root = attrs(open).filter(([k]) => !ROOT_DROP.has(k))

    const body = [...src.matchAll(TAG)]
      .map(([, el, chunk]) => `<${el}${svelteAttrs(attrs(chunk))} />`)
      .join("")

    components.push(
      `export const ${pascal(name)} = createIcon(${svelteObj(root)}, ${JSON.stringify(body)})`
    )
  }

  return {
    text: `${svelteHeader(rel)}\n${components.join("\n")}\n`,
    count: components.length,
    rel,
  }
}

const built = []
for (const mod of SVELTE_MODULES)
  built.push({ ...mod, ...(await build(mod.style, mod.corners)) })

if (check) {
  let drift = false
  for (const { rel, outs, text } of built) {
    for (const [label, path] of outs) {
      const prev = existsSync(path) ? await readFile(path, "utf8") : null
      if (prev === text) continue
      const why = prev === null ? "does not exist" : `is out of sync with ${rel}/`
      console.error(`  ${c(33, "DRIFT")} ${label} ${why}`)
      drift = true
    }
  }
  if (drift) {
    console.error(`\nRun: node pipeline/build-svelte.mjs`)
    process.exit(1)
  }
  const targets = built.reduce((n, m) => n + m.outs.length, 0)
  const summary = built
    .map((m) => `${m.corners === "sharp" ? "sharp " : ""}${m.style} ${m.count}`)
    .join(", ")
  console.log(c(32, `${targets} generated Svelte modules in sync with icons/ (${summary})`))
} else {
  for (const { outs, text, count } of built) {
    for (const [label, path] of outs) {
      await mkdir(dirname(path), { recursive: true })
      await writeFile(path, text, "utf8")
      console.log(`Wrote ${count} components to ${label}`)
    }
  }
}
