import type { MetadataRoute } from "next"

import { SITE_DESCRIPTION } from "@/lib/seo"
import { SET_NAME, SET_TITLE } from "@/lib/site-chrome"

/**
 * The web app manifest, served at `/manifest.webmanifest`.
 *
 * Next picks this up by filename and emits the `<link rel="manifest">` itself,
 * so there is nothing to wire in `layout.tsx` — the same arrangement as
 * `icon.svg`, `favicon.ico` and `apple-icon.png`, and the same hazard: nothing
 * type-checks the result, and a manifest that fails to parse simply stops
 * existing with no error on the page that links it.
 *
 * This is the Android half of a pair. The iOS half is already there and is
 * spelled differently: `appleWebApp` in `layout.tsx` names the home-screen
 * shortcut and `app/apple-icon.png` draws it, because iOS reads neither the
 * name nor the icons out of a manifest. Change what the site is called and both
 * halves move.
 */
export default function manifest(): MetadataRoute.Manifest {
  return {
    // A stable identity for the installed app, independent of `start_url`.
    // Without it the browser derives one from the start URL, and moving the
    // start URL later would register as a different app rather than an update.
    id: "/",
    name: SET_TITLE,
    // Roughly twelve characters is what a home-screen label holds before it is
    // truncated, so this is the set's name without the noun: "Keyline", not
    // "Keyline Icons".
    short_name: SET_NAME,
    description: SITE_DESCRIPTION,
    start_url: "/",
    scope: "/",
    lang: "en",
    dir: "ltr",
    // Chrome only offers to install a site whose display is one of standalone,
    // fullscreen or minimal-ui.
    display: "standalone",
    /*
     * Both are the page's own background, and both are one fixed value.
     *
     * A manifest cannot read the theme any more than a favicon can: the theme
     * is a class on `<html>` and this is a separate document, and unlike
     * `icon.svg` there is not even a `prefers-color-scheme` to fall back on. So
     * the choice is which theme to be wrong in, and light is the one that costs
     * least — `theme_color` tints the Android toolbar, and the site bar is
     * `bg-background` with no border, so white keeps the browser's chrome and
     * the site's chrome the same surface. A `--primary` toolbar would put a
     * near-black band above a white page.
     *
     * These are `--background` in the light theme resolved to a literal, the
     * way `pipeline/build-brand.mjs` carries `--primary` as one. If that token
     * moves, this moves with it by hand.
     */
    background_color: "#ffffff",
    theme_color: "#ffffff",
    categories: ["design", "developer", "productivity"],
    /*
     * Generated by `pipeline/build-brand.mjs` from `public/logo/logo.svg`, and
     * in `public/` rather than `app/` because Next's app-icon convention has no
     * room for a file named after its size. The note on `MANIFEST_SIZES` there
     * carries the rest, including why one bled rendering can be both `any` and
     * `maskable`.
     *
     * Which is why each file appears twice. The spec makes `purpose` a
     * space-separated set and `"any maskable"` is the ordinary way to say this,
     * but Next types the field as a single keyword and rejects it, so the two
     * purposes become two entries over the same PNG.
     *
     * Both are needed, and the missing one is not the obvious half. Given only
     * `any`, Android pads the icon into a white circle and the mark comes back
     * shrunken with a light rim — the same mistake the apple icon avoids by
     * bleeding. Given only `maskable`, anywhere that wants an unmasked icon
     * has none to use.
     */
    icons: [
      {
        src: "/logo/icon-192.png",
        sizes: "192x192",
        type: "image/png",
        purpose: "any",
      },
      {
        src: "/logo/icon-192.png",
        sizes: "192x192",
        type: "image/png",
        purpose: "maskable",
      },
      {
        src: "/logo/icon-512.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "any",
      },
      {
        src: "/logo/icon-512.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "maskable",
      },
    ],
  }
}
